### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MatthewScholefield** [severin-lemaignan/webcam-v4l2#5]
@severin-lemaignan I submitted PR #2 a while back but didn't realize there was no LICENSE file. Mind adding in something like an [MIT](https://opensource.org/licenses/MIT) license?

**Comment by severin-lemaignan** [comment]
Thanks for pointing out the missing license. Added a MIT license in  80a25b4.

**Comment by severin-lemaignan** [comment]
Ooops! The project has to be LGPL as I was reusing LGPL components! Sorry about that! If you'd rather having your previous commit removed because of that, I can do so, of course.

**Comment by MatthewScholefield** [comment]
No problem that's fine.
